### ISSUE TITLE
System.PlatformNotSupportedException: Accessing a hash algorithm

### ISSUE THREAD

**Issue by vipul3010** [microsoft/slngen#149]
I am still seeing the issue  #145 happening in the latest Microsoft.VisualStudio.SlnGen.Tool. If there is no instance of visual studio 2019 running and I use slngen to open a project built on net46(also tried on project built on net472) then I see the following error:
Unhandled exception. System.AggregateException: One or more errors occurred. (Accessing a hash algorithm by manipulating the HashName property is not supported on this platform. Instead, you must instantiate one of the supplied subtypes (such as HMACSHA1.))
 ---> System.PlatformNotSupportedException: Accessing a hash algorithm by manipulating the HashName property is not supported on this platform. Instead, you must instantiate one of the supplied subtypes (such as HMACSHA1.)
   at System.Security.Cryptography.HMAC.HashCore(Byte[] rgb, Int32 ib, Int32 cb)
   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
   at Microsoft.VisualStudio.ApplicationInsights.Channel.Transmission.HashContent(Byte[] content)
   at Microsoft.VisualStudio.ApplicationInsights.Channel.Transmission.get_ContentHash()
   at Microsoft.VisualStudio.ApplicationInsights.Channel.StorageTransmission.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object arg0, Object arg1)
   at Microsoft.VisualStudio.ApplicationInsights.Channel.Sender.SendAsync(StorageTransmission transmission, CancellationToken token, TimeSpan sendInterval)
   at Microsoft.VisualStudio.ApplicationInsights.Channel.Sender.<>c__DisplayClass20_1.<<FlushAll>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ApplicationInsights.Channel.Sender.FlushAll(CancellationToken token)
   at Microsoft.VisualStudio.ApplicationInsights.Channel.PersistenceTransmitter.Flush(CancellationToken token)
   at Microsoft.VisualStudio.ApplicationInsights.Channel.PersistenceChannel.FlushAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.ApplicationInsights.TelemetryClient.FlushAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.Telemetry.SessionChannel.BaseAppInsightsClientWrapper.DisposeAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.Telemetry.SessionChannel.BaseAppInsightsSessionChannel.DisposeAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.Telemetry.EventProcessorRouter.DisposeAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.Telemetry.EventProcessorContext.DisposeAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.Telemetry.EventProcessor.DisposeAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.Telemetry.SessionChannel.EventProcessorChannel.DisposeAndTransmitAsync(CancellationToken token)
   at Microsoft.VisualStudio.Telemetry.TelemetrySession.DisposeToNetworkAsync(CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Microsoft.VisualStudio.SlnGen.TelemetryClient.Dispose() in C:\A\_work\107\s\src\Microsoft.VisualStudio.SlnGen\TelemetryClient.cs:line 48
   at Microsoft.VisualStudio.SlnGen.Program.Main(String[] args) in C:\A\_work\107\s\src\Microsoft.VisualStudio.SlnGen\Program.cs:line 253

**Comment by jeffkl** [comment]
Thanks for reporting.  My previous fix only caught `PlatformNotSupportedException` but this is an `AggregateException` with an inner `PlatformNotSupportedException`.  I'll get a fix out ASAP.

**Comment by vipul3010** [comment]
Yeah the Wait at the end rolls the PlatformNotSupportedException inside an AggregateException. Thanks for fixing it quickly.
