### ISSUE TITLE
Generation fails when using msbuild.exe from Visual Studio 2017

### ISSUE THREAD

**Issue by tokizr** [microsoft/slngen#324]
Example setup (single empty project):
```
dotnet new console -o Test
```

Steps to reproduce:
Start the Developer Command Prompt for VS 2017 (so it's msbuild.exe is on PATH):
cd to the example directory.
run `slngen --launch false -o Test.sln Test/Test.csproj `

Output:
```
SlnGen version 8.1.0+e9b8452b83 for .NET Framework
Copyright (c) Microsoft Corporation.  Licensed under the MIT license.

System.MissingMethodException: Method not found: 'Void Microsoft.Build.Evaluation.ProjectCollection..ctor(System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IEnumerable`1<Microsoft.Build.Framework.ILogger>, System.Collections.Generic.IEnumerable`1<Microsoft.Build.Logging.ForwardingLoggerRecord>, Microsoft.Build.Evaluation.ToolsetDefinitionLocations, Int32, Boolean, Boolean)'.
   at Microsoft.VisualStudio.SlnGen.Program.GetProjectCollection(ILogger[] loggers)
   at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<OnExecute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__186`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at Microsoft.VisualStudio.SlnGen.Program.Execute(String[] args, IConsole console)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

See comments on #278 .

**Comment by tokizr** [comment]
Same result with SlnGen version 8.2.1+f7a0759e8c. I tried with -bl but it did not produce any files.
