### ISSUE TITLE
Generation fails when using Wildcards and msbuild.exe from Visual Studio 2019

### ISSUE THREAD

**Issue by tokizr** [microsoft/slngen#325]
Example setup (two empty projects):
```
dotnet new console -o Test1
dotnet new console -o Test2
```

Steps to reproduce:
Start the Developer Command Prompt for VS 2019 (so it's msbuild.exe is on PATH):
cd to the example directory.
run `slngen --launch false -o Test.sln */*.csproj `

Output:
```
SlnGen version 8.1.0+e9b8452b83 for .NET Framework
Copyright (c) Microsoft Corporation.  Licensed under the MIT license.

Build started 2022-01-11 12:42:28.
SlnGen : error : Unhandled exception: System.ArgumentException: Illegal characters in path.
SlnGen : error :    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
SlnGen : error :    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
SlnGen : error :    at System.IO.Path.GetFullPath(String path)
SlnGen : error :    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.ProgramArguments.TryGetEntryProjectPaths(ISlnGenLogger logger, IReadOnlyList`1& projectEntryPaths)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)

Failed

SlnGen : error : Unhandled exception: System.ArgumentException: Illegal characters in path.
SlnGen : error :    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
SlnGen : error :    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
SlnGen : error :    at System.IO.Path.GetFullPath(String path)
SlnGen : error :    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.ProgramArguments.TryGetEntryProjectPaths(ISlnGenLogger logger, IReadOnlyList`1& projectEntryPaths)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)
    0 Warning(s)
    1 Error(s)
```

Same command works fine when VS's msbuild.exe is not on path (and msbuild.dll from the .Net SDK is used instead).

**Comment by KevinSchiener** [comment]
I experience the same problem. Direct path to the project file works as intended. Wildcards, even *.csproj causes the exception.

Using Developer Command Prompt for VS 2022

**Comment by mciancia8** [comment]
This happened to me too

**Comment by mciancia8** [comment]
I found the issue, the extension method for Contains is wrong

Here is what it is, the "str" and "value" are swapped inside the method

public static bool Contains(this string str, string value, StringComparison comparisonType)
        {
            return value.IndexOf(str, comparisonType) >= 0;
        }
