### ISSUE TITLE
System.InvalidOperationException: Instance object was created as immutable in MSBuild 17.4

### ISSUE THREAD

**Issue by jeffkl** [microsoft/slngen#420]
In MSBuild 17.4, static graph changed to merge project reference targets.

https://github.com/dotnet/msbuild/pull/7837

This means that SlnGen can't load projects as immutable or we need MSBuild to do this operation in another way.

```
Loading project references...
SlnGen : error : System.InvalidOperationException: Instance object was created as immutable.
SlnGen : error :    at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
SlnGen : error :    at Microsoft.Build.Graph.GraphBuilder.GraphEdges.<>c.<AddOrUpdateEdge>b__5_1(ValueTuple`2 key, ProjectItemInstance existingItem, ProjectItemInstance newItem)
SlnGen : error :    at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate[TArg](TKey key, Func`3 addValueFactory, Func`4 updateValueFactory, TArg factoryArgument)
SlnGen : error :    at Microsoft.Build.Graph.GraphBuilder.GraphEdges.AddOrUpdateEdge(ValueTuple`2 key, ProjectItemInstance edge)
SlnGen : error :    at Microsoft.Build.Graph.GraphBuilder.AddEdgesFromProjectReferenceItems(Dictionary`2 allParsedProjects, GraphEdges edges)
SlnGen : error :    at Microsoft.Build.Graph.GraphBuilder.AddEdges(Dictionary`2 allParsedProjects)
SlnGen : error :    at Microsoft.Build.Graph.GraphBuilder.BuildGraph()
SlnGen : error :    at Microsoft.Build.Graph.ProjectGraph..ctor(IEnumerable`1 entryPoints, ProjectCollection projectCollection, ProjectInstanceFactoryFunc projectInstanceFactory, Int32 degreeOfParallelism, CancellationToken cancellationToken)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.ProjectLoading.ProjectGraphProjectLoader.LoadProjects(IEnumerable`1 projectPaths, ProjectCollection projectCollection, IDictionary`2 globalProperties)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.ProjectLoading.ProjectLoader.LoadProjects(FileInfo msbuildExeFileInfo, ProjectCollection projectCollection, IEnumerable`1 entryProjects, IDictionary`2 globalProperties, ISlnGenLogger logger)
```

**Comment by jeffkl** [comment]
Originally reported by @inthemedium
