### ISSUE TITLE
SlnGen fails under VsDevCmd environment.

### ISSUE THREAD

**Issue by jogietze** [microsoft/slngen#436]
The "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" batch file sets up the PATH environment variable to include, for example:

`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\\MSBuild\Current\Bin\amd64`

Your detection logic here...

https://github.com/microsoft/slngen/blob/main/src/Shared/DevelopmentEnvironment.cs#L182

...appends an extra `amd64` without checking if the path exists, and fails:

> ```
> D:\src>slngen
> Unhandled exception: System.IO.FileNotFoundException: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\amd64\MSBuild.exe
>   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
>   at Microsoft.VisualStudio.SlnGen.Program.Main(String[] args) in D:\a\_work\1\s\src\Microsoft.VisualStudio.SlnGen.Tool\Program.cs:line 81
> ```

**Comment by jeffkl** [comment]
That logic is in an `if` statement for only when the current runtime is 64-bit but the `MSBuild.exe` found is not 64-bit.  Is this from a 32-bit development environment?  I'm curious how its finding the 64-bit `MSBuild.exe` but doesn't think the current process is already 64-bit.

**Comment by jeffkl** [comment]
@jogietze Have you tried the latest version and still hit this?  I think I saw it happen yesterday but when I updated SlnGen to the latest version it started working.

**Comment by jogietze** [comment]
The issue comes and goes.  It's reasonably easy to work around by updating `%PATH%`.

**Comment by jefflomax** [comment]
https://github.com/CommunityToolkit/Windows.git as of 2026-04-11
Building on ARM64 Copilot PC, running in Developer PowerShell or Developer command prompt  (VS2022 or VS2026) 
fails, making this a poor experience.

dotnet tool update microsoft.visualstudio.slngen.tool
to  12.0.32
Does fix it, but it didn't the first time, restart the terminal, verify dotnet tool list does show the right version.

But there is no reason to not **just commit a working, common feature set CommunityToolkit.AllComponents.sln**    It shouldn't take hours of searching why GenerateAllSolution.bat blows up just to get to see the project.   

If there is a reason for SlnGen to even EXIST, which is debatable, then at least leave it for advanced users. Don't make a dependency on this tool that will NEVER BE RELIABLE for all your first time users.
