### ISSUE TITLE
Support MSBuild Target for .NET 7 and 8

### ISSUE THREAD

**Issue by ryanerdmann** [microsoft/slngen#460]
The [MSBuild Target](https://microsoft.github.io/slngen/#getting-started-msbuild-target) feature of SlnGen is not supported with the .NET 7 or 8 SDK.

### Description

`Microsoft.VisualStudio.SlnGen.targets` [explicitly hardcodes](https://github.com/microsoft/slngen/blob/a6afb307fc4f900ea4b9d25de14a26293797fe7f/src/Microsoft.VisualStudio.SlnGen/Microsoft.VisualStudio.SlnGen.targets#L26) the .NET 6 build of the MSBuild tasks in `slngen.dll`, which fails to load when hosted in the .NET 7/8 MSBuild flavors.

```xml
  <UsingTask TaskName="Microsoft.VisualStudio.SlnGen.Tasks.SlnGenToolTask"
             AssemblyFile="$([MSBuild]::ValueOrDefault('$(SlnGenAssemblyFile)', '$(MSBuildThisFileDirectory)..\tools\net6.0\slngen.dll'))"
             Condition="'$(MSBuildRuntimeType)' == 'Core' And '$(MSBuildVersion)' &gt;= '17.0.0'" />
```

### Repro

```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SlnGen" Version="9.5.5" DevelopmentDependency="true" />
  </ItemGroup>

</Project>
```

Repro Steps: 
```
C:\Users\rerdmann>dotnet --version
7.0.103

C:\Users\rerdmann>dotnet msbuild slngen-repro.csproj /t:SlnGen /v:d
```

Which results in the following stack:

```
dotnet C:\Users\rerdmann\.nuget\packages\microsoft.visualstudio.slngen\9.5.5\tools\net6.0\slngen.dll --nologo --verbosity:Normal --consolelogger:NoSummary;ForceNoAlign C:\Users\rerdmann\source\repos\slngen-repro\slngen-repro.csproj
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)
at Microsoft.VisualStudio.SlnGen.ProgramArguments.OnExecute(IConsole console)
--- End of stack trace from previous location ---
at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
at Microsoft.VisualStudio.SlnGen.Program.Execute(String[] args, IConsole console)
```

### Suggested Fix and Workarounds

It seems that the MSBuild target should load the `slngen.dll` that matches the current SDK/MSBuild runtime.

As a workaround, the `SlnGenAssemblyFile` property can be set in a target: `<SlnGenAssemblyFile>$(PkgMicrosoft_VisualStudio_SlnGen)\tools\net7.0\slngen.dll</SlnGenAssemblyFile>`.

Alternatively, the .NET Tool variant (which was supported in previous work, #362) works correctly for projects built using the .NET 7 or 8 SDKs.

**Comment by jeffkl** [comment]
Thanks for filing this, I'll get a fix out today.

**Comment by ryanerdmann** [comment]
Thanks for the quick turnaround, and for publishing an updated NuGet package!  Pulled this in and confirmed everything works great.  Thanks!
