### ISSUE TITLE
The solution folder is not created properly if the driver letters are different.

### ISSUE THREAD

**Issue by Say-Y** [microsoft/slngen#512]
I want to easily merge my new projects with "my engine projects" like Unreal Engine.
This is possible if you are on the same driver using the following command:

Directory.Build.props (in my engine dir)
```
<Project>
  <ImportGroup Label="Shared">
    <Import Project="$(SolutionDir)**\*.vcxitems" Label="Shared" />
  </ImportGroup>
</Project>
```
GenerateSolution.bat (in my engine dir)
```
setlocal
set SolutionName=%1
IF [%1] == [] set SolutionName=Engine

slngen %2 **\*.vcxproj **\*.csproj **\*.vcxitems --platform x64 --configuration Debug;Release --folders:true --collapsefolders:false --ignoreMainProject --solutionfile:"%3%SolutionName%.sln"

REM --binarylogger

REM GenerateSolution.bat SolutionName Project SolutionPath
REM Example) GenerateSolution.bat Test "D:\MyProject\Source\Project.vcxitems" D:\MyProject\
```

If the driver with the engine is the same as the new project it will succeed, otherwise it will fail. (Solution folder was not created properly)
Are there any other ways or fixes planned?

Failed log
```
Generating solution for project "C:\MyProject\Source\Project.vcxitems"
Generating solution for project "D:\Engine\Engine\Source\Editor\Editor.vcxproj"
Generating solution for project "D:\Engine\Engine\Source\Runtime\Core\Core.vcxitems"
Generating solution for project "D:\Engine\Engine\Source\Runtime\Network\Network.vcxitems"
Generating solution for project "D:\Engine\Engine\Source\Runtime\Renderer\Renderer.vcxitems"
Loading project references...
Loaded 5 project(s) in 78ms
Generating Visual Studio solution "C:\MyProject\Test.sln" ...
Updating existing solution file and reusing Visual Studio cache
SlnGen : error : Unhandled exception: System.ArgumentException: The path is empty. (Parameter 'path')
SlnGen : error :    at System.IO.Path.GetFullPath(String path)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.ExtensionMethods.ToRelativePath(String path, String relativeTo)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.SlnFile.Save(String rootPath, TextWriter writer, Boolean useFolders, Boolean collapseFolders, Boolean alwaysBuild)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.SlnFile.Save(String path, Boolean useFolders, Boolean collapseFolders, Boolean alwaysBuild)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.SlnFile.GenerateSolutionFile(ProgramArguments arguments, IEnumerable`1 projects, ISlnGenLogger logger)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)

Failed

SlnGen : error : Unhandled exception: System.ArgumentException: The path is empty. (Parameter 'path')
SlnGen : error :    at System.IO.Path.GetFullPath(String path)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.ExtensionMethods.ToRelativePath(String path, String relativeTo)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.SlnFile.Save(String rootPath, TextWriter writer, Boolean useFolders, Boolean collapseFolders, Boolean alwaysBuild)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.SlnFile.Save(String path, Boolean useFolders, Boolean collapseFolders, Boolean alwaysBuild)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.SlnFile.GenerateSolutionFile(ProgramArguments arguments, IEnumerable`1 projects, ISlnGenLogger logger)
SlnGen : error :    at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)

...

 00:00:00.13
System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.VisualStudio.SlnGen.ExtensionMethods.ToRelativePath(String path, String relativeTo)
   at Microsoft.VisualStudio.SlnGen.SlnFile.Save(String rootPath, TextWriter writer, Boolean useFolders, Boolean collapseFolders, Boolean alwaysBuild)
   at Microsoft.VisualStudio.SlnGen.SlnFile.Save(String path, Boolean useFolders, Boolean collapseFolders, Boolean alwaysBuild)
   at Microsoft.VisualStudio.SlnGen.SlnFile.GenerateSolutionFile(ProgramArguments arguments, IEnumerable`1 projects, ISlnGenLogger logger)
   at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)
   at Microsoft.VisualStudio.SlnGen.ProgramArguments.OnExecute(IConsole console)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at Microsoft.VisualStudio.SlnGen.Program.Execute(String[] args, IConsole console)

```

**Comment by jeffkl** [comment]
@Say-Y can you please create an empty solution on one drive and then manually add existing projects in Visual Studio to two or more projects on two or more different drives and let me know what the resulting solution file looks like?  I'd be interested if Visual Studio supports this as I know it generally places relative paths in the solution file.  If Visual Studio supports it, I think SlnGen should as well.

**Comment by Say-Y** [comment]
Sorry for the late reply.
It has been confirmed that it works well in Visual Studio.

```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.7.34031.279
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ConsoleApplication1", "D:\ConsoleApplication1\ConsoleApplication1.vcxproj", "{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "StaticLib1", "E:\Source\StaticLib1\StaticLib1.vcxproj", "{994F92AF-F5AC-4B31-8543-4E4DC66AC463}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x64.ActiveCfg = Debug|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x64.Build.0 = Debug|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x86.ActiveCfg = Debug|Win32
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x86.Build.0 = Debug|Win32
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x64.ActiveCfg = Release|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x64.Build.0 = Release|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x86.ActiveCfg = Release|Win32
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x86.Build.0 = Release|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x64.ActiveCfg = Debug|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x64.Build.0 = Debug|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x86.ActiveCfg = Debug|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x86.Build.0 = Debug|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x64.ActiveCfg = Release|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x64.Build.0 = Release|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x86.ActiveCfg = Release|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x86.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {889CF804-97CF-4CAA-8A59-478D24E33B31}
	EndGlobalSection
EndGlobal

```

**Comment by Say-Y** [comment]
What's interesting is that, if it's the same directory as the 'sln' file, it appears to use a relative path.

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.7.34031.279
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ConsoleApplication1", "D:\ConsoleApplication1\ConsoleApplication1.vcxproj", "{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "StaticLib1", "E:\Source\StaticLib1\StaticLib1.vcxproj", "{994F92AF-F5AC-4B31-8543-4E4DC66AC463}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ConsoleApplication3", "..\ConsoleApplication3\ConsoleApplication3\ConsoleApplication3.vcxproj", "{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x64.ActiveCfg = Debug|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x64.Build.0 = Debug|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x86.ActiveCfg = Debug|Win32
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Debug|x86.Build.0 = Debug|Win32
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x64.ActiveCfg = Release|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x64.Build.0 = Release|x64
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x86.ActiveCfg = Release|Win32
		{FDE98FE9-9EC2-47D9-9468-0520C50BE01D}.Release|x86.Build.0 = Release|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x64.ActiveCfg = Debug|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x64.Build.0 = Debug|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x86.ActiveCfg = Debug|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Debug|x86.Build.0 = Debug|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x64.ActiveCfg = Release|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x64.Build.0 = Release|x64
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x86.ActiveCfg = Release|Win32
		{994F92AF-F5AC-4B31-8543-4E4DC66AC463}.Release|x86.Build.0 = Release|Win32
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Debug|x64.ActiveCfg = Debug|x64
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Debug|x64.Build.0 = Debug|x64
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Debug|x86.ActiveCfg = Debug|Win32
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Debug|x86.Build.0 = Debug|Win32
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Release|x64.ActiveCfg = Release|x64
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Release|x64.Build.0 = Release|x64
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Release|x86.ActiveCfg = Release|Win32
		{3F86D74D-E09F-4D44-8DA0-E4F6E1DFB3DC}.Release|x86.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {889CF804-97CF-4CAA-8A59-478D24E33B31}
	EndGlobalSection
EndGlobal
```

**Comment by jeffkl** [comment]
Okay good to know.  I guess we'd need to update the algorithm in SlnGen to detect when two or more projects are on different disks and then use absolute paths instead.  We might need to emit a warning or message letting the user know that we don't recommend they commit those kind of solution files to source control since they don't contain simple relative paths and are not guaranteed to work across machines.

A pull request for this functionality would be gladly accepted.

**Comment by mruxmohan4** [comment]
Closing this as this has been deployed in `v11.2.3` release.
